- tools/askomics/askomics.xml
- tools/askomics/macros.xml
- tools/askomics/test-data/people.tsv
@abretaud 
This tools allow the integration of galaxy datasets into a distant [AskOmics](https://github.com/askomics/askomics) .
Supported inputs: tabular, gff3, bed and ttl.
All options available by the askomics interface can be set with this tool.
> Adding askomics tool

- tools/apollo/create_or_update_organism.xml
- tools/tripal/README.rst
- tools/tripal/analysis_load_fasta.xml
Just a little bug fix, I leave it open for now in case I find other bugs
> tripal: fix error when inserting fasta

- README.md
- tools/apollo/webapollo.py
> Fix bug in group list

- tools/apollo/create_account.py
- tools/apollo/create_features_from_gff3.py
- tools/apollo/webapollo.py
- tools/askomics/macros.xml
- tools/tripal/tripal.py
> AskOmics: Remove url and api key

- tools/apollo/README.rst
- tools/apollo/create_account.py
- tools/apollo/create_account.xml
- tools/apollo/create_features_from_gff3.py
- tools/apollo/create_features_from_gff3.xml
- tools/apollo/create_or_update_organism.xml
- tools/apollo/delete_features.xml
- tools/apollo/delete_organism.xml
- tools/apollo/export.py
- tools/apollo/export.xml
- tools/apollo/fetch_organism_jbrowse.xml
- tools/apollo/json2iframe.xml
- tools/apollo/list_organisms.xml
- tools/apollo/macros.xml
- tools/apollo/webapollo.py
untested? but `builtins` is crashing our prod so...
> Swap to six completely

- tools/chado/macros.xml
- tools/chado/organism_add_organism.xml
An update to the 2.1.3 bugfix release of python-chado
> Update to python-chado 2.1.3

- tools/chado/macros.xml
2.1.3 still contained a bad bug, this one should be better
> Chado tools: update to 2.1.4

- tools/chado/feature_load_fasta.xml
- tools/chado/feature_load_gff.xml
- tools/chado/macros.xml
- tools/tripal/analysis_load_go.xml
- tools/tripal/macros.xml
- tools/tripal/organism_add_organism.xml
- tools/tripal/phylogeny_sync.xml
Here's another update of python-chado to fix an annoying bug
I also fixed a problem with sanitizing regex params
And also updated the tripal wrappers to the 3.0 version of python-tripal (which I had completely forgotten)
And now, week-end!
Cheers
> Chado and tripal updates+fixes

- tools/chado/feature_load_fasta.xml
Just tiny fix for the broken --update option of python-chado/feature/load_fasta
> chado: fix --update option for load_fasta

- tools/chado/feature_load_fasta.xml
- tools/chado/feature_load_featureprops.xml
- tools/chado/feature_load_gff.xml
- tools/chado/phylogeny_gene_families.xml
- tools/chado/phylogeny_gene_order.xml
- tools/chado/phylogeny_load_tree.xml
Simplified the boolean parameters + added a fix for the strange https://github.com/galaxyproject/galaxy/issues/6663 problem
> Small boolean fixes for Chado tools

- tools/chado/macros.xml
oops, I forgot to update the tool version in previous PR...
> python-chado: forgot to update tool version

- tools/chado/analysis_add_analysis.xml
- tools/chado/analysis_delete_analyses.xml
- tools/chado/analysis_get_analyses.xml
- tools/chado/chado.py
- tools/chado/export_export_fasta.xml
- tools/chado/export_export_gbk.xml
- tools/chado/export_export_gff3.xml
- tools/chado/expression_add_biomaterial.xml
- tools/chado/expression_add_expression.xml
- tools/chado/expression_delete_all_biomaterials.xml
- tools/chado/expression_delete_biomaterials.xml
- tools/chado/expression_get_biomaterials.xml
- tools/chado/feature_delete_features.xml
- tools/chado/feature_get_features.xml
- tools/chado/feature_load_fasta.xml
- tools/chado/feature_load_featureprops.xml
- tools/chado/feature_load_gff.xml
- tools/chado/feature_load_go.xml
- tools/chado/macros.xml
- tools/chado/organism_add_organism.xml
- tools/chado/organism_delete_all_organisms.xml
- tools/chado/organism_delete_organism.xml
- tools/chado/organism_get_organisms.xml
- tools/chado/phylogeny_gene_families.xml
- tools/chado/phylogeny_gene_order.xml
- tools/chado/phylogeny_load_tree.xml
A fix for a little bug I found while using the latest tool update...
> python-chado: fix wrong param name in load_gff

- tools/tripal/analysis_get_analyses.xml
- tools/tripal/db_index.xml
- tools/tripal/entity_publish.xml
- tools/tripal/expression_add_biomaterial.xml
- tools/tripal/expression_add_expression.xml
- tools/tripal/expression_delete_biomaterials.xml
- tools/tripal/expression_get_biomaterials.xml
- tools/tripal/expression_sync_biomaterials.xml
- tools/tripal/feature_delete_orphans.xml
- tools/tripal/macros.xml
- tools/tripal/organism_get_organisms.xml
Thanks to @mboudet's work, now supports loading expression data.
These new tools are not tested yet. I have to do it (sigh)
> Tripal tools: update to python-tripal 3.1.1

- tools/chado/macros.xml
> Update to python-chado 2.2.5

- tools/apollo/create_or_update_organism.py
- tools/apollo/create_or_update_organism.xml
- Moved the file copying to the python script and added safeguards
- Convert .fasta to .2bit, and add the path to it to the organism in Apollo
> Add support form blatdb

- tools/chado/phylogeny_load_tree.xml
3 little fixes for the load_tree tool:
- auth was broken
- a typo in a condition
- output type is not json
> Fixes for chado phylogeny load_tree

- tools/apollo/create_or_update_organism.py
- tools/chado/analysis_add_analysis.xml
- tools/chado/organism_add_organism.xml
2 little things:
- keep symlinks as is when sending a jbrowse dataset to apollo
- add the analysis/organism name in the dataset name when creating new ones
> Small apollo/chado improvement

- .travis.yml
- tools/chado/analysis_add_analysis.xml
- tools/chado/analysis_delete_analyses.xml
- tools/chado/analysis_get_analyses.xml
- tools/chado/export_export_fasta.xml
- tools/chado/export_export_gbk.xml
- tools/chado/export_export_gff3.xml
- tools/chado/expression_add_biomaterial.xml
- tools/chado/expression_add_expression.xml
- tools/chado/expression_delete_all_biomaterials.xml
- tools/chado/expression_delete_biomaterials.xml
- tools/chado/expression_get_biomaterials.xml
- tools/chado/feature_delete_features.xml
- tools/chado/feature_get_features.xml
- tools/chado/feature_load_fasta.xml
- tools/chado/feature_load_featureprops.xml
- tools/chado/feature_load_gff.xml
- tools/chado/feature_load_go.xml
- tools/chado/macros.xml
- tools/chado/organism_add_organism.xml
- tools/chado/organism_delete_all_organisms.xml
- tools/chado/organism_delete_organism.xml
- tools/chado/organism_get_organisms.xml
- tools/chado/phylogeny_gene_families.xml
- tools/chado/phylogeny_gene_order.xml
- tools/chado/phylogeny_load_tree.xml
- tools/chado/prepare_psql.sh
Doing the same as https://github.com/bgruening/galaxytools/pull/642 with Chado database
It works! Just need to update the remaining tools
> [WIP] Add support for pgtools/pgutil for chado tools

- tools/chado/analysis_add_analysis.xml
- tools/chado/analysis_delete_analyses.xml
- tools/chado/analysis_get_analyses.xml
- tools/chado/export_export_fasta.xml
- tools/chado/export_export_gbk.xml
- tools/chado/export_export_gff3.xml
- tools/chado/expression_add_biomaterial.xml
- tools/chado/expression_add_expression.xml
- tools/chado/expression_delete_all_biomaterials.xml
- tools/chado/expression_delete_biomaterials.xml
- tools/chado/expression_get_biomaterials.xml
- tools/chado/feature_delete_features.xml
- tools/chado/feature_get_features.xml
- tools/chado/feature_load_fasta.xml
- tools/chado/feature_load_featureprops.xml
- tools/chado/feature_load_gff.xml
- tools/chado/feature_load_go.xml
- tools/chado/macros.xml
- tools/chado/organism_add_organism.xml
- tools/chado/organism_delete_all_organisms.xml
- tools/chado/organism_delete_organism.xml
- tools/chado/organism_get_organisms.xml
- tools/chado/phylogeny_gene_families.xml
- tools/chado/phylogeny_gene_order.xml
- tools/chado/phylogeny_load_tree.xml
So there was some bugs in #40 when *not* using pgtools, this will fix them.
(I replaced the macro-inside-a-macro as it is broken in galaxy <19.05)
> Fix things broken by #40

- tools/apollo/create_account.xml
- tools/apollo/create_features_from_gff3.xml
- tools/apollo/create_or_update_organism.xml
- tools/apollo/delete_features.xml
- tools/apollo/delete_organism.xml
- tools/apollo/export.xml
- tools/apollo/fetch_organism_jbrowse.xml
- tools/apollo/json2iframe.py
- tools/apollo/json2iframe.xml
- tools/apollo/list_organisms.xml
- tools/apollo/macros.xml
per bug report from Nathan in email.
Also:
- add apollo as a citation (if you're using the tools you should be citing apollo)
- sync up versions
haven't cited us yet, but, we should get a paper out soon and then fix that :)
> Remove tracklist forced on

- tools/tripal/db_index.xml
- tools/tripal/entity_publish.xml
- tools/tripal/expression_add_biomaterial.xml
- tools/tripal/expression_add_expression.xml
- tools/tripal/macros.xml
Some minor changes I forgot to push earlier
Also now the tool will use TRIPAILLE_GLOBAL_CONFIG_PATH if it's already defined by galaxy admin
> Small fixes to tripal tools

- tools/chado/macros.xml
An update to 2.3.1 which is a small bugfix release
> Update to python-chado 2.3.1

- tools/chado/macros.xml
> Update python-chado to 2.3.2

- .travis.yml
- tools/apollo/macros.xml
Fixes #53
ping @MoffMade @hexylena 
So I guess we'll need to update the tools on our galaxy instances + remove older versions + change the apollo admin account password
> Update apollo tools to python-apollo 4.2.5

- tools/jbrowse/jbrowse_to_container.py
- tools/jbrowse/macros.xml
Time to get rid of python2 here too...
> jbrowse_to_container: migrate to python3

- .github/workflows/pr.yaml
- tools/chado/macros.xml
Just a minor release with one bug fix
> Update to python-chado 2.3.7
